Linebreak fix.
joysticktv/joysticktv.github.io pull request #68
Opened 2024-12-20 23:11 UTC by Adachi91

All the text in non-bulleted list is lumped together. (Fixes #67)

Also added the ?response_type=code to the `example` field.

I'm so terribly sorry for all these, I hope this fixes things.

2024-12-20 23:32 UTC, jwoertink requested changes

2024-12-20 23:32 UTC, jwoertink commented on developer_support.md
> +`scope` - "bot" &mdash; Not used currently.<br />
```suggestion
* `response_type` - Required &mdash; the value must be set to `code`
* `client_id` - Required &mdash; Your bot's Client ID
* `scope` - "bot" &mdash; Not used currently.
```

All of the examples below just use an unordered list, so it's probably easiest to just copy that flow.

2024-12-21 10:08 UTC, Adachi91 commented on developer_support.md
> +`scope` - "bot" &mdash; Not used currently.<br />
Revised to recommendations in adachi91/joysticktv.github.io@63086e9

2024-12-22 23:24 UTC, jwoertink approved these changes

2024-12-22 23:25 UTC, merged